name: Build Godot Pirateban project

on:
  push:
    branches: ['dev']  

jobs:
  Godot:
    runs-on: self-hosted
    strategy:
      matrix:
        platform: [mac]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: Pirateban
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
